### ISSUE TITLE
`getetags` not sent by all servers(?)

### ISSUE THREAD

**Issue by dario23** [gkbrk/carddav-rs#1]
hi,

first of all, very happy to see someone starting work on a carddav library :-)

i tried it with my own server (davical 1.1.5/debian stretch), and found that my server doesn't send `getetag` responses, which makes `addressbooks()` fail in [line 127]([https://github.com/gkbrk/carddav-rs/blob/master/src/lib.rs#L127).

the way i understand [the rfc](https://tools.ietf.org/html/rfc6352#section-6.3.2.3) on that, `getetag` does not neccessarily need to be set on addressbooks, only on "address object resources" (= individual vcard items)

edit: i testet on [https://www.caldavserver.com/](https://www.caldavserver.com/) as well (they seem to be using some windows server software), with similar results; what server did you develop with?

**Comment by gkbrk** [comment]
I was just testing with FastMail. Thanks a lot for the caldavserver.com link, it's going to be really useful to have more servers to test against.
